#!/bin/bash

# written Apr. 30. 2019
# by Yunjae Hwang, yunjaeh@stanford.edu

# This script is to connect MATLAB to OpenModelica
# Pre-processing is required : change target parameter(number) to the name(string)
#				and the model name (optional)

# ---------- list of files ---------- #
FILE_SCRIPT='OutfallUQScript.mos'			    # OpenModelica script that runs model
FILE_OUTPUT='./workspace/OM_Result_res.csv'     # output result file
FILE_FILTERED='./workspace/OUTPUT_FILTERED.dat' # Filtered output file that contains only variables we need (do not filter to compare temperature data as well

# FILE_OUTPUT='./OM_Result_res.csv'     # output result file
# FILE_FILTERED='./OUTPUT_FILTERED.dat' # Filtered output file that contains only variables we need (do not filter to compare temperature data as well
# Template files
#   : strings in template files will be replaced with values(numbers) sampled in the 
FILE_TEMPLATE='Outfall.mo.template'		        
VENTILATION_TEMPLATE='Single_ventilation.mo.template'

# Model files
#   : Actual files that are going to run
FILE_MODEL='Outfall.mo'		
VENTILATION_MODEL='Single_ventilation.mo'

PREFIX_RESULT='OM_Result'

# list of directory
DIR_MODELICA=$(pwd)

# print summary
# echo $'\n\tSummary\n'
# echo "File	: $FILE_TEMPLATE -> $FILE_MODEL"
# echo "Script 	: $FILE_SCRIPT"
# echo "Directory : $DIR_MODELICA"
# echo "Data 	: $DIR_MODELICA/workspace/$PREFIX_RESULT"



## read parameters from a input file
# nominal parameters
VAL_DATA_DATE=$(awk 'NR==1{print $0}' UQ_input.in) 
VAL_HEIGHT_1=$(awk 'NR==2{print $0}' UQ_input.in)
# VAL_HEIGHT_2=$(awk 'NR==3{print $0}' UQ_input.in) 
VAL_AREA_OPENING_1=$(awk 'NR==4{print $0}' UQ_input.in) 
# VAL_AREA_OPENING_2=$(awk 'NR==5{print $0}' UQ_input.in) 

# uncertain parameters
VAL_CONVECTION_COEF_INNER=$(awk 'NR==6{print $0}' UQ_input.in) 
VAL_CONVECTION_COEF_OUTER=$(awk 'NR==7{print $0}' UQ_input.in)
VAL_CONDUCTIVITY_WALL=$(awk 'NR==8{print $0}' UQ_input.in) 
VAL_CONDUCTIVITY_ROOF=$(awk 'NR==9{print $0}' UQ_input.in) 
VAL_EMISSIVITY_WALL=$(awk 'NR==10{print $0}' UQ_input.in) 
VAL_EMISSIVITY_ROOF=$(awk 'NR==11{print $0}' UQ_input.in) 
# VAL_CD_OPENING_1=$(awk 'NR==12{print $0}' UQ_input.in) 
# VAL_CD_OPENING_2=$(awk 'NR==13{print $0}' UQ_input.in) 
VAL_INFILTRATION=$(awk 'NR==12{print $0}' UQ_input.in) 

 
# echo '-----------------------------------------'
# echo $'\n	Start to change parameters\n'
# echo '-----------------------------------------'
echo 'Height and area of openings'
sed "s/HEIGHT_1/$VAL_HEIGHT_1/g" $VENTILATION_TEMPLATE > $VENTILATION_MODEL
sed -i "s/HEIGHT_2/$VAL_HEIGHT_2/g" $VENTILATION_MODEL
sed -i "s/AREA_OPENING_1/$VAL_AREA_OPENING_1/g" $VENTILATION_MODEL
sed -i "s/AREA_OPENING_2/$VAL_AREA_OPENING_2/g" $VENTILATION_MODEL

echo 'Data date'
sed "s/DATA_DATE/$VAL_DATA_DATE/g" $FILE_TEMPLATE > $FILE_MODEL

echo "Convection - chage heat transfer coefficient"
sed -i "s/CONVECTION_COEF_INNER/$VAL_CONVECTION_COEF_INNER/g"  $FILE_MODEL
sed -i "s/CONVECTION_COEF_OUTER/$VAL_CONVECTION_COEF_OUTER/g" $FILE_MODEL

echo 'Infiltration - pre factor'
sed -i "s/CONDUCTIVITY_WALL/$VAL_CONDUCTIVITY_WALL/g" $FILE_MODEL
sed -i "s/CONDUCTIVITY_ROOF/$VAL_CONDUCTIVITY_ROOF/g" $FILE_MODEL
sed -i "s/EMISSIVITY_WALL/$VAL_EMISSIVITY_WALL/g" $FILE_MODEL
sed -i "s/EMISSIVITY_ROOF/$VAL_EMISSIVITY_ROOF/g" $FILE_MODEL
sed -i "s/INFILTRATION/$VAL_INFILTRATION/g" $FILE_MODEL

# echo 'Area and discharge coefficient of two openings'
# sed "s/AREA_OPENING_1/$VAL_AREA_OPENING_1/g" $AREA_TEMPLATE > $AREA_MODEL
# sed -i "s/AREA_OPENING_2/$VAL_AREA_OPENING_2/g" $AREA_MODEL
# sed -i "s/CD_OPENING_1/$VAL_CD_OPENING_1/g" $AREA_MODEL
# sed -i "s/CD_OPENING_2/$VAL_CD_OPENING_2/g" $AREA_MODEL



# echo '-----------------------------------------'
# echo $'\n\tChange Done\n'
# echo '-----------------------------------------'
# cat $FILE_MODEL

# clear workspace
mkdir ./workspace
# rm ./workspace/*
# Writing ".mos" script (to assign simulation paramters)
echo $'\n\tWrite .mos script\n'
echo "cd(\"$DIR_MODELICA\");" >> $FILE_SCRIPT
echo "loadModel(Modelica);" > $FILE_SCRIPT
echo "loadFile(\"$FILE_MODEL\");" >> $FILE_SCRIPT
echo "loadFile(\"$VENTILATION_MODEL\");" >> $FILE_SCRIPT
echo "cd(\"$DIR_MODELICA/workspace\");" >> $FILE_SCRIPT
echo "simulate(Outfall,outputFormat=\"csv\",fileNamePrefix=\"$PREFIX_RESULT\");" >> $FILE_SCRIPT

# echo "simulate(Outfall,outputFormat=\"csv\",fileNamePrefix=\"$PREFIX_RESULT\",variableFilter=\"natural_ventilation1.Ventilation_rate.y\");" >> $FILE_SCRIPT
# cat $FILE_SCRIPT

echo $'\n\tSimulation Start\n'
# echo "omc $FILE_SCRIPT"
omc $FILE_SCRIPT


# filtering variables
f_indoor=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Temperature_Indoor.T' | awk -F: '{print$1}' )
f_wall=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_wall1_outer.port_b.T' | awk -F: '{print$1}' )
f_wall_in=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_wall1_inner.port_b.T' | awk -F: '{print$1}' )
f_wall_out=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_wall1_outer.port_a.T' | awk -F: '{print$1}' )
f_roof=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_roof_outer.port_b.T' | awk -F: '{print$1}' )
f_roof_in=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_roof_inner.port_b.T' | awk -F: '{print$1}' )
f_roof_out=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_roof_outer.port_a.T' | awk -F: '{print$1}' )
f_vrate=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'two_single_ventilation1.Ventilation_rate.y' | awk -F: '{print$1}' )
awk -F, '{print $'$f_indoor',$'$f_wall',$'$f_wall_in',$'$f_wall_out',$'$f_roof',$'$f_roof_in',$'$f_roof_out',$'$f_vrate'}' $FILE_OUTPUT > $FILE_FILTERED  




# cp $OUTPUT_TEMP $OUTPUT_SAVE
# cut -d"," $OUTPUT_SAVE >> ACH.txt

# echo "1" >> result.txt
# cp ./workspace/*.csv ./Save_result/
