#!/bin/bash

# First written: Apr. 30. 2019
# Last modified: Aug. 27. 2019
# by Yunjae Hwang, yunjaeh@stanford.edu

FILE_OUTPUT=$1
FILE_FILTERED=$2
# -------------------- filter output files -------------------- #
# filtering variables
f_outdoor=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'OutdoorTemperature.y' | awk -F: '{print$1}' )
f_radiation=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'SolarRadiation.y' | awk -F: '{print$1}' )
f_wind=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'WindSpeed.y' | awk -F: '{print$1}' )
f_radiation=101
f_wind=106
f_indoor=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Temperature_Indoor.T' | awk -F: '{print$1}' )
f_wall=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_wall1_outer.port_b.T' | awk -F: '{print$1}' )
f_wall_in=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_wall1_inner.port_b.T' | awk -F: '{print$1}' )
f_wall_out=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_wall1_outer.port_a.T' | awk -F: '{print$1}' )
f_roof=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_roof_outer.port_b.T' | awk -F: '{print$1}' )
f_roof_in=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_roof_inner.port_b.T' | awk -F: '{print$1}' )
f_roof_out=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_roof_outer.port_a.T' | awk -F: '{print$1}' )
f_vrate=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'two_single_ventilation1.Ventilation_rate.y' | awk -F: '{print$1}' )
awk -F, '{print $'$f_outdoor',$'$f_radiation',$'$f_wind',$'$f_indoor',$'$f_wall',$'$f_wall_in',$'$f_wall_out',$'$f_roof',$'$f_roof_in',$'$f_roof_out',$'$f_vrate'}' $FILE_OUTPUT > $FILE_FILTERED  
# cp $FILE_OUTPUT $FILE_FILTERED



