#!/bin/bash

# First written: Apr. 30. 2019
# Last modified: Aug. 27. 2019
# by Yunjae Hwang, yunjaeh@stanford.edu

# This script is to connect MATLAB to OpenModelica
# Pre-processing is required : change target parameter(number) to the name(string)
#				and the model name (optional)


# -------------------- file list -------------------- #
### Script, output file names
FILE_SCRIPT='OutfallUQScript.mos'			    # OpenModelica script that compiles and runs model
FILE_OUTPUT='./workspace/OM_Result_res.csv'     # output result file
FILE_FILTERED='./workspace/OUTPUT_FILTERED.dat' # Filtered output file that contains only variables we need (do not filter to compare temperature data as well

### Templates: strings in template files will be replaced with values(numbers)
MAIN_TEMPLATE='Outfall.mo.template'		        
VENTILATION_TEMPLATE='Two_single_ventilation.mo.template'

### Models: Actual files that are going to run
MAIN_MODEL='Outfall.mo'		
VENTILATION_MODEL='Two_single_ventilation.mo'
PREFIX_RESULT='OM_Result'


# -------------------- directory -------------------- #
DIR_MODELICA=$(pwd)


# -------------------- parameters -------------------- #
## read parameters from a input file
# nominal parameters
VAL_DATA_DATE=$(awk 'NR==1{print $0}' UQ_input.in) 
VAL_HEIGHT_1=$(awk 'NR==2{print $0}' UQ_input.in)
VAL_HEIGHT_2=$(awk 'NR==3{print $0}' UQ_input.in) 
VAL_AREA_OPENING_1=$(awk 'NR==4{print $0}' UQ_input.in) 
VAL_AREA_OPENING_2=$(awk 'NR==5{print $0}' UQ_input.in) 


# -------------------- directory -------------------- #
# uncertain parameters
VAL_CONVECTION_COEF_INNER=$(awk 'NR==6{print $0}' UQ_input.in) 
VAL_CONVECTION_COEF_OUTER=$(awk 'NR==7{print $0}' UQ_input.in)
# VAL_CONDUCTIVITY_ROOF=$(awk 'NR==8{print $0}' UQ_input.in) 
# VAL_CONDUCTIVITY_WALL=$(awk 'NR==9{print $0}' UQ_input.in) 
# VAL_EMISSIVITY_ROOF=$(awk 'NR==10{print $0}' UQ_input.in) 
# VAL_EMISSIVITY_WALL=$(awk 'NR==11{print $0}' UQ_input.in) 
VAL_REFLECTANCE_ROOF=$(awk 'NR==8{print $0}' UQ_input.in) 
VAL_VENTILATION_RATE_1=$(awk 'NR==9{print $0}' UQ_input.in) 
VAL_VENTILATION_RATE_2=$(awk 'NR==10{print $0}' UQ_input.in) 
VAL_INFILTRATION=$(awk 'NR==11{print $0}' UQ_input.in) 

# add input factors (outdoor temperature, radiation, wind)
VAL_QT_TEMPERATURE=$(awk 'NR==12{print $0}' UQ_input.in) 
VAL_QT_RADIATION=$(awk 'NR==13{print $0}' UQ_input.in) 
VAL_QT_WIND=$(awk 'NR==14{print $0}' UQ_input.in) 

 
# -------------------- substitution -------------------- #
### 1. Area and height of openings
sed "s/HEIGHT_1/$VAL_HEIGHT_1/g" $VENTILATION_TEMPLATE > $VENTILATION_MODEL
sed -i "s/HEIGHT_2/$VAL_HEIGHT_2/g" $VENTILATION_MODEL
sed -i "s/AREA_OPENING_1/$VAL_AREA_OPENING_1/g" $VENTILATION_MODEL
sed -i "s/AREA_OPENING_2/$VAL_AREA_OPENING_2/g" $VENTILATION_MODEL

### 2. Coefficients in ventilation models
sed -i "s/VENTILATION_RATE_1/$VAL_VENTILATION_RATE_1/g" $VENTILATION_MODEL
sed -i "s/VENTILATION_RATE_2/$VAL_VENTILATION_RATE_2/g" $VENTILATION_MODEL

### 3. Date 
sed "s/DATA_DATE/$VAL_DATA_DATE/g" $MAIN_TEMPLATE > $MAIN_MODEL

### 4. Heat transfer coefficients
sed -i "s/CONVECTION_COEF_INNER/$VAL_CONVECTION_COEF_INNER/g"  $MAIN_MODEL
sed -i "s/CONVECTION_COEF_OUTER/$VAL_CONVECTION_COEF_OUTER/g" $MAIN_MODEL
# sed -i "s/CONDUCTIVITY_WALL/$VAL_CONDUCTIVITY_WALL/g" $MAIN_MODEL
# sed -i "s/CONDUCTIVITY_ROOF/$VAL_CONDUCTIVITY_ROOF/g" $MAIN_MODEL
# sed -i "s/EMISSIVITY_WALL/$VAL_EMISSIVITY_WALL/g" $MAIN_MODEL
# sed -i "s/EMISSIVITY_ROOF/$VAL_EMISSIVITY_ROOF/g" $MAIN_MODEL
sed -i "s/REFLECTANCE_ROOF/$VAL_REFLECTANCE_ROOF/g" $MAIN_MODEL
sed -i "s/INFILTRATION/$VAL_INFILTRATION/g" $MAIN_MODEL

### 5. Pre-factors for input parameters
sed -i "s/QT_TEMPERATURE/$VAL_QT_TEMPERATURE/g" $MAIN_MODEL
sed -i "s/QT_RADIATION/$VAL_QT_RADIATION/g" $MAIN_MODEL
sed -i "s/QT_WIND/$VAL_QT_WIND/g" $MAIN_MODEL

# echo 'Area and discharge coefficient of two openings'
# sed "s/AREA_OPENING_1/$VAL_AREA_OPENING_1/g" $AREA_TEMPLATE > $AREA_MODEL
# sed -i "s/AREA_OPENING_2/$VAL_AREA_OPENING_2/g" $AREA_MODEL
# sed -i "s/CD_OPENING_1/$VAL_CD_OPENING_1/g" $AREA_MODEL
# sed -i "s/CD_OPENING_2/$VAL_CD_OPENING_2/g" $AREA_MODEL


# -------------------- write and run MOS script -------------------- #

# clear workspace
mkdir ./workspace

echo $'\n\tWrite .mos script\n'
echo "cd(\"$DIR_MODELICA\");" >> $FILE_SCRIPT
echo "loadModel(Modelica);" > $FILE_SCRIPT
echo "loadFile(\"$MAIN_MODEL\");" >> $FILE_SCRIPT
echo "loadFile(\"$VENTILATION_MODEL\");" >> $FILE_SCRIPT
echo "cd(\"$DIR_MODELICA/workspace\");" >> $FILE_SCRIPT
echo "simulate(Outfall,outputFormat=\"csv\",fileNamePrefix=\"$PREFIX_RESULT\");" >> $FILE_SCRIPT

# echo "simulate(Outfall,outputFormat=\"csv\",fileNamePrefix=\"$PREFIX_RESULT\",variableFilter=\"natural_ventilation1.Ventilation_rate.y\");" >> $FILE_SCRIPT
# cat $FILE_SCRIPT

echo $'\n\tSimulation Start\n'
# echo "omc $FILE_SCRIPT"
omc $FILE_SCRIPT

# First written: Apr. 30. 2019
# Last modified: Aug. 27. 2019
# by Yunjae Hwang, yunjaeh@stanford.edu

# FILE_OUTPUT=$1
# FILE_FILTERED=$2
# -------------------- filter output files -------------------- #
# filtering variables
f_outdoor=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n '\"OutdoorTemperature\"' | awk -F: '{print$1}' )
f_radiation=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'SolarRadiation' | awk -F: '{print$1}' )
f_wind=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'WindSpeed' | awk -F: '{print$1}' )
f_indoor=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Temperature_Indoor.T' | awk -F: '{print$1}' )
f_wall=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_wall1_outer.port_b.T' | awk -F: '{print$1}' )
f_wall_in=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_wall1_inner.port_b.T' | awk -F: '{print$1}' )
f_wall_out=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_wall1_outer.port_a.T' | awk -F: '{print$1}' )
f_roof=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_roof_outer.port_b.T' | awk -F: '{print$1}' )
f_roof_in=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_roof_inner.port_b.T' | awk -F: '{print$1}' )
f_roof_out=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'Conduction_roof_outer.port_a.T' | awk -F: '{print$1}' )
f_vrate=$(head -n 1 $FILE_OUTPUT | tr ',' '\n' | grep -n 'two_single_ventilation1.Ventilation_rate.y' | awk -F: '{print$1}' )


awk -F, '{print $'$f_outdoor',$'$f_radiation',$'$f_wind',$'$f_indoor',$'$f_wall',$'$f_wall_in',$'$f_wall_out',$'$f_roof',$'$f_roof_in',$'$f_roof_out',$'$f_vrate'}' $FILE_OUTPUT > $FILE_FILTERED  

# cp $FILE_OUTPUT $FILE_FILTERED




# cp $OUTPUT_TEMP $OUTPUT_SAVE
# cut -d"," $OUTPUT_SAVE >> ACH.txt

# echo "1" >> result.txt
# cp ./workspace/*.csv ./Save_result/
